//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNIdesu.Dex {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HNIdesu.Dex.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;nop&quot;:&quot;0x0&quot;,
        ///	&quot;move&quot;:&quot;0x1&quot;,
        ///	&quot;move/from16&quot;:&quot;0x2&quot;,
        ///	&quot;move/16&quot;:&quot;0x3&quot;,
        ///	&quot;move-wide&quot;:&quot;0x4&quot;,
        ///	&quot;move-wide/from16&quot;:&quot;0x5&quot;,
        ///	&quot;move-wide/16&quot;:&quot;0x6&quot;,
        ///	&quot;move-object&quot;:&quot;0x7&quot;,
        ///	&quot;move-object/from16&quot;:&quot;0x8&quot;,
        ///	&quot;move-object/16&quot;:&quot;0x9&quot;,
        ///	&quot;move-result&quot;:&quot;0xA&quot;,
        ///	&quot;move-result-wide&quot;:&quot;0xB&quot;,
        ///	&quot;move-result-object&quot;:&quot;0xC&quot;,
        ///	&quot;move-exception&quot;:&quot;0xD&quot;,
        ///	&quot;return-void&quot;:&quot;0xE&quot;,
        ///	&quot;return&quot;:&quot;0xF&quot;,
        ///	&quot;return-wide&quot;:&quot;0x10&quot;,
        ///	&quot;return-object&quot;:&quot;0x11&quot;,
        ///	&quot;const/4&quot;:&quot;0x12&quot;,
        ///	&quot;const/16&quot;:&quot;0x13&quot;,
        ///	&quot;const&quot;:&quot;0x14&quot;,
        ///	&quot;const/high16&quot;:&quot;0x15&quot;,
        ///	&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OperationList {
            get {
                return ResourceManager.GetString("OperationList", resourceCulture);
            }
        }
    }
}
